[run]
build = "npm run build"

[gptengineer-app]
project_id = "75774bc0-71c3-45a3-9caf-1073a95982de"

[[gptengineer-app.openapi]]
url = "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/color.pizza/1.0.0/openapi.yaml"
